CREATE TABLE settings (id INTEGER PRIMARY KEY AUTOINCREMENT, active BOOLEAN);
CREATE TABLE votes (id INTEGER PRIMARY KEY AUTOINCREMENT, direction INTEGER, fromNumber VARCHAR, active BOOLEAN);

INSERT INTO settings (active) VALUES (1);